Repository Kernel360/Kernel360-KDEV4-ZIPLINE-FE, pull requests merged in 2025-05, with the labels that each got.

#75 fix: 로그인 API 요청 시 401 에러 발생할 때 reissue 호출 방지
  src/apis/apiClient.ts
Labels: 🛠️ Fix

#90 feat: 상담 목록, 상담 상세 조회
  src/pages/CounselDetailPage/CounselDetailPage.tsx
  src/pages/CounselDetailPage/styles/CounselDetailPage.module.css
  src/pages/CounselListPage/CounselListPage.tsx
  src/pages/CounselListPage/CounselModal.tsx
  src/pages/CounselListPage/styles/CounselListPage.module.css
Labels: ✨ Feat

#92 hotfix: 일정 추가 전용 모달 사용하도록 리팩토링
  src/components/CreateModal/CreateModal.tsx
  src/components/NavigationBar/NavigationBar.tsx
  src/pages/SchedulePage/AddScheduleModal/AddScheduleModal.tsx
  src/pages/SchedulePage/AddScheduleModal/index.ts
  src/pages/SchedulePage/SchedulePage.tsx
Labels: ⚙️ Refactor, 🔥 HotFix

#98 feat: 고객 목록 페이지 디자인 수정
  src/pages/CustomerListPage/CustomerListPage.tsx
  src/pages/CustomerListPage/CustomerTable/CustomerTable.tsx
  src/pages/CustomerListPage/CustomerTable/DeleteConfirmModal.tsx
Labels: ✨ Feat

#102 design: 고객 상세 페이지 디자인 수정
  src/pages/CustomerDetailPage/CustomerDetailPage.tsx
  src/pages/CustomerDetailPage/CustomerInfo/CustomerInfo.tsx
  src/pages/CustomerDetailPage/Tables/ConsultationTable.tsx
  src/pages/CustomerDetailPage/Tables/ContractTable.tsx
  src/pages/CustomerDetailPage/Tables/PropertyTable.tsx
Labels: ✨ Feat, 🌸 design

#147 fix: 설문 - 파일 업로드가 안되는 버그 수정
  src/pages/SubmitSurveyPage/SubmitSurveyPage.tsx
Labels: 🛠️ Fix

#177 fix: 계약 목록 - 계약 카테고리 null 값 안보이도록 수정
  src/pages/ContractListPage/ContractAddButtonList/ContractEditModal/ContractEditModal.tsx
  src/pages/DashboardPage/RecentContractsModal.tsx
Labels: 🛠️ Fix
